### ISSUE TITLE
使用 MatterJS 后无法自动横屏

### ISSUE THREAD

**Issue by iSunday** [layabox/layaair#10]
```
Laya.stage.alignV = Stage.ALIGN_MIDDLE;
Laya.stage.alignH = Stage.ALIGN_CENTER;

Laya.stage.scaleMode = "showall";
Laya.stage.screenMode = Stage.SCREEN_HORIZONTAL;
```
无法横屏，如何解决？谢谢

**Comment by Surviver** [comment]
你是指按照那样设置后，鼠标交互失效了？

**Comment by iSunday** [comment]
@Surviver 

谢谢你回复，我找到问题了，在 render -> options 中的 background 图片大小是会影响到画布大小的

**Comment by iSunday** [comment]
@Surviver 

不过设置了横屏后，在移动端鼠标交互确实会失效，这个如何解决？

**Comment by Surviver** [comment]
实际上，任何平台上，使画布横屏都是让Matte.js的交互失效。因为Matter.js的鼠标交互是它自身控制的，但是显示是LayaAir控制的，LayaAir旋转了画布方向，但是Matter.js不会旋转。所以你想要横屏只能通过系统的横屏，不能再竖屏状态下使用”横屏显示“。

**Comment by iSunday** [comment]
@Surviver 

这个没办法通过代码来解决吗？

**Comment by Surviver** [comment]
除非改Matter.js的代码，将获取的鼠标坐标也旋转了。但由于要修改第三方库，所以至少我们不会去修改。
