### ISSUE TITLE
建议让Camera.worldToViewportPoint能得到是在屏幕前，还是屏幕后

### ISSUE THREAD

**Issue by eos3tion** [layabox/LayaAir#101]
https://github.com/layabox/LayaAir/blob/master/src/layaAir/laya/d3/core/Camera.ts#L662-L667

目前Camera设计的接口，out.z 并无法得知，当前3d坐标，在屏幕上的映射，是在屏幕前面，还是屏幕后面，通常只有在屏幕前面的需要进行显示，而屏幕后的无法显示  
  
https://github.com/layabox/LayaAir/blob/master/src/layaAir/laya/d3/math/Viewport.ts#L46-L62
中，project方法，计算的得到的`a`，并未返回，原本可以根据此数据的正负关系，得知是在屏幕前，还是屏幕后的  

建议优化这两个接口可以将此数据返回，以便区分正负关系
我自己的处理是将`Viewport.ts`的`project`方法修改为：
```ts
project(source: Vector3, matrix: Matrix4x4, out: Vector3) {
		var sX: number = source.x;
		var sY: number = source.y;
		var sZ: number = source.z;
		Vector3.transformV3ToV3(source, matrix, out);
		var matE: Float32Array = matrix.elements;
		var a: number = (((sX * matE[3]) + (sY * matE[7])) + (sZ * matE[11])) + matE[15];
		if (a !== 1.0) {//待优化，经过计算得出的a可能会永远只近似于1，因为是Number类型
			out.x = out.x / a;
			out.y = out.y / a;
			out.z = out.z / a;
		}

		out.x = (((out.x + 1.0) * 0.5) * this.width) + this.x;
		out.y = (((-out.y + 1.0) * 0.5) * this.height) + this.y;
		out.z = (out.z * (this.maxDepth - this.minDepth)) + this.minDepth;
		return a;
	}
```
Camera.ts的`worldToViewportPoint`修改为
```ts
worldToViewportPoint(position: Vector3, out: Vector3): void {
		Matrix4x4.multiply(this._projectionMatrix, this._viewMatrix, this._projectionViewMatrix);
		let a = this.viewport.project(position, this._projectionViewMatrix, out);
		out.x = out.x / Laya.stage.clientScaleX;
		out.y = out.y / Laya.stage.clientScaleY;
		return a;
	}
```

**Comment by GuoLei1990** [comment]
你说的“屏幕后”是超过远裁面范围吧? 目前worldToViewportPoint接口返回的Z返回范围是采用深度为0到1的标准  也就是近裁面的位置恰好是0，远裁面的范围恰好是1 Z值不在0到1内视为不在摄像机渲染范围

**Comment by eos3tion** [comment]
@GuoLei1990 不是说的远裁剪面，而是说的近裁剪面。3d的点投影到Viewport这个平面上时，是可以在前面，也可以在后面，你们现在的写法就是把点投影到Viewport平面的写法，原本可以通过`a`的正负关系得到是在平面前，还是平面后的。现在这个值并没有返回。

**Comment by GuoLei1990** [comment]
如果说近材面的话确实Z的返回结果不是很友好，现在的Z值可能还不如直接返回`a`更实用，你说的也确实是一种解决方案

**Comment by GuoLei1990** [comment]
https://github.com/layabox/LayaAir/commit/83be5a6309bc4553c4d6a6049bc395550e314dd6 分支下已修改,下次发版前会合并
