### ISSUE TITLE
iOS端使用遮罩屏幕会黑屏，必现（附demo项目）

### ISSUE THREAD

**Issue by Captain-Huang** [layabox/LayaAir#108]
iOS端Safari浏览器，laya2.3，使用遮罩界面会黑屏，但过一会又能显示，必现（附demo项目）。这个问题我去论坛找过帖子，发现其他人也有同样问题（别人的问题链接：https://ask.layabox.com/question/44687）。
项目demo：见附件
[TestMask.zip](https://github.com/layabox/LayaAir/files/3831054/TestMask.zip)

**Comment by aaronswiftming** [comment]
这个问题已经反馈到引擎部了

**Comment by tongshuaihuang** [comment]
辛苦回复下这个问题开始解决了吗？
 一个月过去了。。。。
@GuoLei1990

**Comment by aaronswiftming** [comment]
https://ask.layabox.com/question/44687 请参照这个帖子 先修改规避
