### ISSUE TITLE
源码编译异常

### ISSUE THREAD

**Issue by gblw1218** [layabox/LayaAir#1144]
> layaair@3.0.0 build
> gulp build

Debugger attached.
[17:51:56] Using gulpfile G:\GitPrj\Game\LayaAir\gulpfile.js
[17:51:56] Starting 'build'...
[17:51:56] Starting 'compile'...
[17:51:56] Starting 'compileLayaAir'...
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(88,38): error TS2339: Property 'StateParamsMap' does not exist on type 'typeof SubShader'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(106,63): error TS2339: Property 'RENDER_STATE_BLEND' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(122,79): error TS2339: Property 'RENDER_STATE_BLEND_EQUATION' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(123,74): error TS2339: Property 'RENDER_STATE_BLEND_SRC' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(124,74): error TS2339: Property 'RENDER_STATE_BLEND_DST' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(141,82): error TS2339: Property 'RENDER_STATE_BLEND_EQUATION_RGB' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(142,84): error TS2339: Property 'RENDER_STATE_BLEND_EQUATION_ALPHA' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(143,72): error TS2339: Property 'RENDER_STATE_BLEND_SRC_RGB' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(144,72): error TS2339: Property 'RENDER_STATE_BLEND_DST_RGB' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(145,74): error TS2339: Property 'RENDER_STATE_BLEND_SRC_ALPHA' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(146,74): error TS2339: Property 'RENDER_STATE_BLEND_DST_ALPHA' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(183,68): error TS2339: Property 'RENDER_STATE_DEPTH_WRITE' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(184,67): error TS2339: Property 'RENDER_STATE_DEPTH_TEST' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(186,68): error TS2339: Property 'RENDER_STATE_STENCIL_REF' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(187,69): error TS2339: Property 'RENDER_STATE_STENCIL_TEST' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(188,70): error TS2339: Property 'RENDER_STATE_STENCIL_WRITE' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(189,67): error TS2339: Property 'RENDER_STATE_STENCIL_OP' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\d3\RenderObjs\WebGPUOBJ\WGPURenderPipelineInstance.ts(226,62): error TS2339: Property 'RENDER_STATE_CULL' does not exist on type 'typeof Shader3D'.
src\layaAir\laya\RenderEngine\RenderShader\ShaderInstance.ts(12,10): error TS2300: Duplicate identifier 'RenderStateContext'.
src\layaAir\laya\RenderEngine\RenderShader\ShaderInstance.ts(13,10): error TS2300: Duplicate identifier 'ShaderCompileDefineBase'.
src\layaAir\laya\RenderEngine\RenderShader\ShaderInstance.ts(18,10): error TS2300: Duplicate identifier 'RenderStateContext'.
src\layaAir\laya\RenderEngine\RenderShader\ShaderInstance.ts(20,10): error TS2300: Duplicate identifier 'ShaderCompileDefineBase'.
TypeScript: 22 semantic errors
TypeScript: emit succeeded (with errors)
[17:52:05] 'compileLayaAir' errored after 9.64 s
[17:52:05] Error: TypeScript: Compilation failed

**Comment by xiaoguzhu** [comment]
当前稳定版是在分支LayaAir_3.0.0
