### ISSUE TITLE
TrailGeometry开八叉树时会报错

### ISSUE THREAD

**Issue by eos3tion** [layabox/LayaAir#120]
3ca748f6a8fa3b1cfb81078b9972dc27252d762d 对`constructor`时进行了修复，是否漏掉了
`_updateVertexBufferUV` 中 https://github.com/layabox/LayaAir/blob/master/src/layaAir/laya/d3/core/trail/TrailGeometry.ts#L321-L328

当，_disappearBoundsMode时，应该要重置大小
但是遍历大小的代码https://github.com/layabox/LayaAir/blob/master/src/layaAir/laya/d3/core/trail/TrailGeometry.ts#L338
是从 `_activeIndex`开始，而`_disappearBoundsMode`设置为`true`的判断会导致`_activeIndex`和`vertexCount`相等，导致遍历过程并不会执行

现在有两个解决方案
一个是将重新设置 min max的遍历代码，抽出来，从索引`0`开始遍历
要么`L321-L328`改成和`constructor`一致，改为：
```ts
		if (this._disappearBoundsMode) {//如果有顶点消失时候，需要重新计算包围盒
			bounds = this._owner._owner.trailRenderer.bounds;
			var sprite3dPosition: Vector3 = this._owner._owner.transform.position;
			bounds.setMin(sprite3dPosition);
			bounds.setMax(sprite3dPosition);
			min = bounds.getMin();
			max = bounds.getMax();
			Render.supportWebGLPlusCulling && this._calculateBoundingBoxForNative();//[NATIVE]
		}
```

我目前使用的是将,min,max初值改成和constructor的代码一致的方法

@ZhengQixv

**Comment by ZhengQixv** [comment]
1.[3ca748f6a8fa3b1cfb81078b9972dc27252d762d](url)中对`constructor`所进行的修复，的确漏掉了`_updateVertexBufferUV`中相同的操作。
2.在[https://github.com/layabox/LayaAir/blob/e6f135d13f5dd1ade2269acccfd0f37fedff453a/src/layaAir/laya/d3/core/trail/TrailGeometry.ts#L413](url)设置_disappearBoundsMode = true时，是在消失一个片段时就会进行设置，所以，在`_updateVertexBufferUV()`中进行遍历时，`_activeIndex`是不一定等于`vertexCount`的，除非在一帧中所有的拖尾片段都消失了，这大概是不可能的。
