### ISSUE TITLE
功能建议:> layaair2-cmd 添加龙骨动画等 工具功能

### ISSUE THREAD

**Issue by zsytssk** [layabox/LayaAir#128]
功能建议:> layaair2-cmd 添加龙骨动画等 工具功能.
这样就可以将常用功能转换为node 脚本执行 不用打开编辑器...
(layaAir2.4把vs code功能剥离我觉得非常的正确 -- 专注ui编辑功能, 将这个功能做到最好)

**Comment by LayaCharley** [comment]
谢谢建议，不过骨骼工具版本，我们已小范围推出商业版本，可以到官网联系商务微信获得，IDE中的公开版本不是我们重点维护的版本。所以暂时不考虑加进去了。
