### ISSUE TITLE
When running the game on iPhone, the loading animation will reload the website

### ISSUE THREAD

**Issue by dkennnn** [layabox/LayaAir#1306]
I have a problem when building a game on the h5 platform
I tried running the game on Android, Web, PC, MAC, IPAD normally
But when I use my iPhone to run the game on safari, sometimes the loading animation (.sk file) will automatically reload the website.
I tried using xcode to run the iphone emulator and it worked fine, my problem was when using a real iphone
Can anyone give me a solution to this problem?

**Comment by xiaoguzhu** [comment]
I think this is because 'sk' extension is used as  'Safari History Index File' on Apple Safari browser. The solution may be rename 'sk' to something else like 'sk2', and then register a loader for 'sk2'.

`
Loader.registerLoader(["sk2"], Laya.TempletLoader);
`
