### ISSUE TITLE
使用publishTool.bat 打包的时候 缺少方法

### ISSUE THREAD

**Issue by 1037195898** [layabox/LayaAir#133]
这种类型没有准备对应的方法 GetAccessor
这种类型没有准备对应的方法 GetAccessor
这种类型没有准备对应的方法 GetAccessor
这种类型没有准备对应的方法 SetAccessor
这种类型没有准备对应的方法 FirstStatement
这种类型没有准备对应的方法 FirstStatement

**Comment by aaronswiftming** [comment]
有个install.bat先安装一下，然后再用publish

**Comment by 1037195898** [comment]
现在上传的库中没有 install.bat  这个文件啊  是忘记传上来了吗？
