### ISSUE TITLE
3.x修改Text.ts中的图文混排排版模式

### ISSUE THREAD

**Issue by CoderMzx** [layabox/LayaAir#1334]
PR关联 1335
在使用图文混排时,文本会和图片进行居中对齐,超链接中的文本也会居中对齐,这样的显示效果就会很奇怪
<img width="193" alt="image" src="https://github.com/layabox/LayaAir/assets/22463022/5aa52c16-487e-4fa6-b4aa-b585130c28a3">

修改Text.ts中的 **doLayout** -> **endLine**方法,去掉居中显示,结果才是正确的
![image](https://github.com/layabox/LayaAir/assets/22463022/82fec7dc-8fc0-4157-8d9c-d3e4e0bb8d10)
![image](https://github.com/layabox/LayaAir/assets/22463022/eab6c6de-adf0-4d2b-b81e-b58f94ec60eb)

**Comment by xiaoguzhu** [comment]
居中和居底的需求都有，我试试加个选项
