### ISSUE TITLE
List组件中的低级代码错误（复制粘贴侠）

### ISSUE THREAD

**Issue by cceevv** [layabox/LayaAir#1383]
![bug](https://github.com/layabox/LayaAir/assets/45227205/89b9a01a-715e-4093-92ce-f3d0edd54411)

【LayaAir_3.1分支中的List组件】
如图所示，_setHeight 方法中调用了 super._setWidth(value); 错误的拷贝了 _setWidth 方法而没有修改。

**Comment by cceevv** [comment]
应该改为 super._setHeight(value);

**Comment by xiaoguzhu** [comment]
优秀，要不你试试提个pull request解决这个问题？这样你也能成功开源贡献者。
如果不方便，那我来改。

**Comment by cceevv** [comment]
> 优秀，要不你试试提个pull request解决这个问题？这样你也能成功开源贡献者。 如果不方便，那我来改。

提交了哦~🤣
