### ISSUE TITLE
有laya打包安卓过后可以播放的视频播放器吗？

### ISSUE THREAD

**Issue by myomyintko** [layabox/LayaAir#1426]
我这边试了官方的demo iframe 
打包出来过后也无法播放，
试了原生的video标签打包过后也无法播放，
如果不打包的情况下，怎么样都可以播放，打包过后就不可以。（其他的功能都还正常，就是播放视频不正常）
请问有可以成功播放的播放器吗？

**Comment by xiaoguzhu** [comment]
安卓原生不是浏览器，不支持iframe，也不支持video标签。视频播放需求可以通过引擎提供的VideoTexture/VideoNode完成。

**Comment by myomyintko** [comment]
已经尝试使用 vidoetexture 和 video node，打包后在 android 上不起作用
