### ISSUE TITLE
如何给BoxCollider 类增加rotation 属性 ？在编辑模式可以看到旋转效果

### ISSUE THREAD

**Issue by xiao8xiao1** [layabox/LayaAir#144]
box2d的SetAsBox 是可以带 rotation 参数的，但laya封装的BoxCollider 没有rotation 属性
我直接修改 \bin\libs\laya.physics.js  下的 BoxCollider 代码，不能生效

自定义一个类继承ColliderBase，在其中增加rotation 属性，运行时可以生效，**但在编辑模式看不到旋转的效果**
export default class BoxCollider_rot extends Laya.ColliderBase {
        /** @prop {name:rot, tips:"数字类型示例", type:Number, default:0}*/
        this._rot = 0;
...
    _setShape(re = true) {
        var scaleX = (this.owner["scaleX"] || 1);
        var scaleY = (this.owner["scaleY"] || 1);
        this._shape.SetAsBox(this._width / 2 / Laya.Physics.PIXEL_RATIO * scaleX, this._height / 2 / Laya.Physics.PIXEL_RATIO * scaleY, 
            new window.box2d.b2Vec2((this._width / 2 + this._x) / Laya.Physics.PIXEL_RATIO * scaleX, (this._height / 2 + this._y) / Laya.Physics.PIXEL_RATIO * scaleY), 
            this._rot);
        if (re)
            this.refresh();
    }
    get rot() {
        return this._rot;
    }

    set rot(value) {
        this._rot = value;
        if (this._shape) 
            this._setShape();
    }

**Comment by aaronswiftming** [comment]
这个就需要修改LayaAirIDE了， 写项目脚本实现不了
