### ISSUE TITLE
在 Windows PC 的 Chrome 浏览器上运行 3D RPG demo，WebGPU 报错

### ISSUE THREAD

**Issue by catdoc** [layabox/LayaAir#1490]
如题。

报错截图如下：
<img width="442" alt="企业微信截图_140ef50e-bd50-43bf-a5d5-d3a0a0a90efb" src="https://github.com/layabox/LayaAir/assets/4272019/763620d7-ead1-4513-aaf6-624aa8404192">

![企业微信截图_17176769306534](https://github.com/layabox/LayaAir/assets/4272019/7edcf83c-94c9-40ef-9581-60457a6b29be)
![企业微信截图_17176767551730](https://github.com/layabox/LayaAir/assets/4272019/d562aa18-4537-4717-b057-5c1cd3ffacb1)

**Comment by xiaoguzhu** [comment]
<img width="377" alt="image" src="https://github.com/layabox/LayaAir/assets/38777031/331bd46a-2965-42d2-95a3-3483dcc54a17">
勾选启用https
