### ISSUE TITLE
WebGPU 报错 NagaWASM.compileGLSL2WGSL

### ISSUE THREAD

**Issue by catdoc** [layabox/LayaAir#1491]
RPG3D demo 解决了 https2 的 issue 之后遇到了新的 WebGPU 报错, 如下图: 

<img width="1419" alt="image" src="https://github.com/layabox/LayaAir/assets/4272019/c1f5340a-cd20-40fa-98bf-cfa04c5a09b7">

此前 http2 issue: https://github.com/layabox/LayaAir/issues/1490

**Comment by catdoc** [comment]
补充信息：
在 Mac M1 Chrome 浏览器，正常加载进入场景，没报错，点击 “技能” 按钮就会报错 
<img width="248" alt="image" src="https://github.com/layabox/LayaAir/assets/4272019/afbb9bca-ea76-4897-a1cc-71b5ddbea4b6">
 
在 安卓 Chrome 上不能正常运行 RGP3D demo，直接黑屏

**Comment by catdoc** [comment]
<img width="1670" alt="image" src="https://github.com/layabox/LayaAir/assets/4272019/f92a464d-e35b-40cf-8424-7fdb99bff16d">

**Comment by Adonis2016** [comment]
Safari还没有正式支持WebGPU
