### ISSUE TITLE
Laya场景编辑器问题 及 引擎的一个小bug

### ISSUE THREAD

**Issue by myGithub1213456** [layabox/LayaAir#151]
一、1.0的版本还支持层级管理自定义位置，结果2.0就不支持了 用着太难受了 每次都得来回拖动 和 滚动鼠标滚轮 不知道你们引擎方有没有开发应用的 难道就没发现这个问题？想固定死也可以 最起码把层级和控件分到两列啊
二、提交一个引擎bug 
  laya.ui.js中的
    set_scaleX(value) {
	        if (super.get_scaleX() == value)
	            return;
			super.set_scaleX(value);			
			this.event(Laya.Event.RESIZE);
			this._getWidget().resetLayoutX(); // 添加本行后 才正常
	    }
在Scene下的第一子节点 ScaleX变化时，如果没有最后那一行（即现在版本）left、right属性无效
(ScaleY同上)

**Comment by KylinLove** [comment]
1) UI编辑器我们优化了布局，不允许拖动和关闭，也能防止用户误操作。至于将层级和控件分成两列，我们和其他的UI编辑器一样，是支持右键直接添加控件的。
2) 关于引擎bug
2.1) 我们给场景中的第一个子节点设置left，然后点击设置scaleX，left属性保持，scaleX正常缩放。
2.2) 给场景中的第一个子节点设置left，点击设置scaleX和left，均正常。
测试引擎: 2.4.0beta2

**Comment by myGithub1213456** [comment]
> 
> 
>     1. UI编辑器我们优化了布局，不允许拖动和关闭，也能防止用户误操作。至于将层级和控件分成两列，我们和其他的UI编辑器一样，是支持右键直接添加控件的。
> 
>     2. 关于引擎bug
>        2.1) 我们给场景中的第一个子节点设置left，然后点击设置scaleX，left属性保持，scaleX正常缩放。
>        2.2) 给场景中的第一个子节点设置left，点击设置scaleX和left，均正常。
>        测试引擎: 2.4.0beta2

     一、您说的“支持右键直接添加控件”不是特别清楚，毕竟Laya是我用的第一个编辑器，只是想学习下， 还是希望能自定义布局，编辑器的工程和层级不在一列，这样用Basics的时候会更直观方便（只是建议哦）
    二、复现例程如下：
         1.UI：
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class testScaleUI extends Laya.Scene {
		public varPanel:Laya.Panel;
        public static  uiView:any ={"type":"Scene","props":{"width":1920,"height":1080},"compId":2,"child":[{"type":"Box","props":{"y":302,"x":20,"right":20,"name":"scaleShape","left":20,"height":200},"compId":4,"child":[{"type":"Panel","props":{"var":"varPanel","right":10,"left":10,"height":200,"hScrollBarSkin":"comp/hscroll.png"},"compId":5}]}],"loadList":["comp/hscroll.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(testScaleUI.uiView);
        }
    }
    REG("ui.test.testScaleUI",testScaleUI);
}
   
    2.GameConfig.ts
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="exactfit";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/testScale.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;

    }
}
GameConfig.init();

3.Main.ts
import GameConfig from "./GameConfig";
import { ui } from "./ui/layaMaxUI";
class Main {
	constructor() {
		//根据IDE设置初始化引擎		
		if (window["Laya3D"]) Laya3D.init(GameConfig.width, GameConfig.height);
		else Laya.init(GameConfig.width, GameConfig.height, Laya["WebGL"]);
		Laya["Physics"] && Laya["Physics"].enable();
		Laya["DebugPanel"] && Laya["DebugPanel"].enable();
		Laya.stage.scaleMode = GameConfig.scaleMode;
		Laya.stage.screenMode = GameConfig.screenMode;
		Laya.stage.alignV = GameConfig.alignV;
		Laya.stage.alignH = GameConfig.alignH;

		//兼容微信不支持加载scene后缀场景
		Laya.URL.exportSceneToJson = GameConfig.exportSceneToJson;

		//打开调试面板（通过IDE设置调试模式，或者url地址增加debug=true参数，均可打开调试面板）
		if (GameConfig.debug || Laya.Utils.getQueryString("debug") == "true") Laya.enableDebugPanel();
		if (GameConfig.physicsDebug && Laya["PhysicsDebugDraw"]) Laya["PhysicsDebugDraw"].enable();
		if (GameConfig.stat) Laya.Stat.show();
		Laya.alertGlobalError = true;

		//激活资源版本控制，version.json由IDE发布功能自动生成，如果没有也不影响后续流程
		Laya.ResourceVersion.enable("version.json", Laya.Handler.create(this, this.onVersionLoaded), Laya.ResourceVersion.FILENAME_VERSION);

		Laya.stage.on(Laya.Event.RESIZE, this, this.onShapeAdj)
	}

	onVersionLoaded(): void {
		//激活大小图映射，加载小图的时候，如果发现小图在大图合集里面，则优先加载大图合集，而不是小图
		Laya.AtlasInfoManager.enable("fileconfig.json", Laya.Handler.create(this, this.onConfigLoaded));
	}

	onConfigLoaded(): void {

		let newScene: ui.test.testScaleUI = new ui.test.testScaleUI();
		Laya.stage.addChild(newScene);

		for (let i = 0; i < 100; i++) {
			let newImg = new Laya.Image();
			let newSubLabel = new Laya.Label();
			newImg.addChild(newSubLabel);

			newSubLabel.text = "L" + i;
			newSubLabel.fontSize = 40;
			newSubLabel.color = "#080807";
			newSubLabel.pos(20, 50)
			newSubLabel.align = "center"

			newImg.skin = "test/c1.png"
			newImg.x = 100 * i;
			newImg.width = 100;
			newImg.height = 100;


			newScene.varPanel.addChild(newImg);
		}

		//加载IDE指定的场景
		//GameConfig.startScene && Laya.Scene.open(GameConfig.startScene);
	}

	onShapeAdj() {
		let BWidth = Laya.Browser.clientWidth * Laya.Browser.pixelRatio
		let BHeight = Laya.Browser.clientHeight * Laya.Browser.pixelRatio

		let stage = Laya.stage;	 
		let child = stage.getChildAt(0);
		if (child) {
			this.performShapeAdj(child, BWidth / stage.designWidth, BHeight / stage.designHeight);
		}
	}

	performShapeAdj(child, scaleX, scaleY) {

		let grandSon = child._children[0];
		if (grandSon && grandSon._style && grandSon.name === "scaleShape") {
			grandSon.scaleY = 1;
			grandSon.scaleX = scaleY / scaleX;
		}
	}
}
//激活启动类
new Main();

**Comment by myGithub1213456** [comment]
功能：默认浏览器长宽比，可以正常横排显示固定个数Laya图标， 当横向拉伸时，Panel要随浏览器尺寸变化而变化，但是Laya图标不能变形，同时可以显示更多的Laya图标 （例程图片资源：官方例程的不要箱子掉下来）
