### ISSUE TITLE
`soundClass is not a constructor` 离开页面再返回播放声音报错(不是必现)

### ISSUE THREAD

**Issue by zsytssk** [layabox/LayaAir#153]
使用的是laya的es6模块, 而不是laya.xx.js. 
直接使用 import { SoundManager } from 'Laya/media/SoundManager'; 而不是Laya.SoundManager;
使用 Laya.SoundManager 好像不会出现报错(我试了几次没有重现)

![TIM截图20191221130042](https://user-images.githubusercontent.com/2304648/71303363-978ed700-23f2-11ea-8186-893625f773e6.png)
![TIM截图20191221130102](https://user-images.githubusercontent.com/2304648/71303364-9bbaf480-23f2-11ea-9f6a-6a2e80a24b35.png)

**Comment by eos3tion** [comment]
按你的描述，我感觉是你引用关系链的问题，我怀疑你又引了 Laya的那个打包成一个js的文件，又用了es6的import方式，我自己项目全部用Laya新的方式，不引他的lib，全部按 es6 module 再用webpack打包，这块一切正常。

**Comment by zsytssk** [comment]
应该是的, 我的文件中中直接使用 `private sound_manager = SoundManager`, 这肯定在laya 初始化之前就执行了; 那就是说我最好使用`Laya.SoundManager`吗

**Comment by eos3tion** [comment]
应该和你用什么无关，只关乎执行顺序
