### ISSUE TITLE
子类的 set get属性中直接调用父类的set get, 编译成es5报错

### ISSUE THREAD

**Issue by zsytssk** [layabox/LayaAir#154]
我将原来laya项目升级到最新的Laya 2.4.0beta, 自己编译laya的es6 ts源码, 发现一个错误 在es6没有问题转换成es5之后就会报错. 我发现错误出现在UIComponent这个类上, 比方说下面这个过程
`ProgressBar.width(get) -> UIComponent.width(get);`
所有经过这个调用之后原来的this对象都会丢失 变成莫名奇妙的东西;

我找了半天最后发现这和ts转义成es5的机制有关; ts 不支持在子类的 set get属性中直接调用父类的set get属性. 我很久以前也碰到这个问题, babel 可以支持这种转义.
ts官方讨论这个问题很久 https://github.com/microsoft/TypeScript/issues/338, 但是没有改动.
我的理解是: 这个问题无法解决, 即使像babel那样转义, 可能也会导致些不可预知的问题;
我建议把代码改成在子类的set get 中直接调用父类的方法而不是 set get, 比方说
`ProgressBar.width(get) -> UIComponent.get_width();`

关联的网站 https://stackoverflow.com/questions/38717725/why-cant-get-superclasss-property-by-getter-typescript

**Comment by aaronswiftming** [comment]
这是es6转es5出的问题 还是 源码直接编es5出的问题？

**Comment by zsytssk** [comment]
@aaronswiftming 你在说什么 我看不懂啊；
简单的说就是：源码中子类的set get 调用父类的set get ts转义成es5就报错

**Comment by aaronswiftming** [comment]
是编译后的es6转es5  还是 源码直接到es5？ 重点在这句话

**Comment by zsytssk** [comment]
@zsytssk  源码直接到es5

**Comment by aaronswiftming** [comment]
为什么要源码直接到es5，没有这种方案。。。这种个性需求不在服务范围之内。。我们提供了es6转es5

**Comment by zsytssk** [comment]
@aaronswiftming 你能先看看吗，改动起来麻不麻烦。
我直接用webpack打包源码转义成es5，没用你们官方的的转义es5的工具；
用webpack代替gulp这肯定是未来的趋势，你看现在外面打包js工具基本上都是用webpack的（游戏的除外），引擎本身应该给用户提供这种灵活性的自定方式。
这是所有ts转义成es5必然会出现的问题， 这样的问题就是一个潜在的坑；
如果你们比较忙，这个问题可以放在后面；到时候有时间精力再去优化这种方面 也是可以慢慢的提升引擎的。

**Comment by zsytssk** [comment]
@aaronswiftming 像vscode有几千个bug， 许多bug都放在backlog里面
https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3ABacklog
这里面的bug都是 优先级不高或者改动起来有疑问，需要思考清楚；这样有个地方放着这些问题， 也许不是今天但迟早会解决掉的；
作为程序员我也理解你们，本身就很忙， 这种不在计划中可做可不做的事情，基本上不会去做；
但我提这个问题是有实际的需求的， 而且对于引擎本身是有意义的； 我本身提bug也要花费精力的，我也不希望自己的精力最后毫无作用；如果这个问题最后变成那样，我以后基本上不会再提什么bug了；原来论坛中许多问题就是这样的不了了之，这显然会限制laya本身的发展；论坛里面沟通非常没有效率，这种情况也没有什么办法去解决。
github本身提供这种issue这种工具， 给这样的困难提供一个有效的记录+对话的+分类的工具， 我觉得能有效的解决这种问题...
我是有实际的需求 也本着希望laya未来能越来越好的愿望出发的， 你看我提的问题， 以及它的原因， 加上外部连接加上我自己的建议，

**Comment by aaronswiftming** [comment]
首先感谢您的回复，这个问题吧我们目前是没有方案的，以后有精力，或者等这种方式真正流行起来我们会去处理，，而且这个反馈得不到效果的确很让人失望，而且很正常。这种需求目前只有您提出来，如果有很多人提出来，那么这个方案才会被考虑。。希望不要因为这次没有效果，就导致其他本可以优先处理的bug没有被反馈。。 目前主要精力都在IDE打包，其他形式的打包都要靠开发者自行处理了，社区效率低也是因为这个流程开发者不熟悉， 准确描述问题，加附上demo的帖子，都会得到有效的解决的。。主要是沟通这块很容易语义不明确。。您这个问题我和引擎部沟通了，源码直接到es5没有方案。

**Comment by Lurenyiabc** [comment]
可以试试先往es6编，然后用webpack的Babel插件转译

**Comment by zsytssk** [comment]
> 可以试试先往es6编，然后用webpack的Babel插件转译

这个我知道的babel+webpack没有问题，ts-loader+webpack 有问题。

**Comment by Lurenyiabc** [comment]
目前ide也是先往es6编，后面用插件转es5。es5不支持直接调用的super的getset，这个目前应该没什么好办法绕开。可以直接用webpack的babel插件

**Comment by zsytssk** [comment]
我使用ts-loader转成es6, 再用babel转成es5, 这样就没有问题了
