### ISSUE TITLE
ComboBox控件放在Dialog上的时候，选择元素的时候selectHandler不会被调用到

### ISSUE THREAD

**Issue by ts0307** [layabox/LayaAir#161]
ComboBox控件放在Dialog上的时候，选择元素的时候selectHandler没有被调用到，不能获得选择了哪个元素。
原因是因为当界面上有Dialog的时候，Dialog和DialogManager都注册了click事件，拦截了ComboBox的弹出列表的click事件。

**Comment by aaronswiftming** [comment]
去社区 ask.layabox.com  传个复现demo，社区解决
