### ISSUE TITLE
Filters:ColorFilter seems not to work on Laya Skeleton 2D Node

### ISSUE THREAD

**Issue by Lykdraft** [layabox/LayaAir#1643]
Filters:ColorFilter seems not to work on Laya Skeleton 2D Node.

(GlowFilter and BlurFilter work)

**Comment by LayaCharley** [comment]
Laya Skeleton does not support the filter feature. If you want to use filters on skeletal animations, it is recommended to use Spine skeletal animations along with the filter functionality.

**Comment by LayaCharley** [comment]
> Filters:ColorFilter seems not to work on Laya Skeleton 2D Node.
> 
> (GlowFilter and BlurFilter work)


Laya Skeleton does not support the filter feature. If you want to use filters on skeletal animations, it is recommended to use Spine skeletal animations along with the filter functionality.

**Comment by Lykdraft** [comment]
I see.
