### ISSUE TITLE
最新版本中WebGLRTMgr的优化调整造成mask泄漏问题

### ISSUE THREAD

**Issue by lzsong** [layabox/LayaAir#166]
![image](https://user-images.githubusercontent.com/7005666/71656876-2945ff00-2d78-11ea-8076-376b62f1d6cb.png)
![image](https://user-images.githubusercontent.com/7005666/71656969-9e193900-2d78-11ea-8345-204ead26d9e8.png)

在2.1之后的版本优化造成了比较严重的问题
如果序列帧动画用了mask遮罩，会在RenderSprite的_mask中每帧都会调用WebGLRTMgr.getRT来new RenderTexture2D，不缓存会无限增长Resource，而且只调用了_disposeResource没有从Resource._urlResourcesMap中释放掉。

**Comment by guozhaokui** [comment]
这个会在后面的 RenderSprite.recycleTarget 部分删除掉，实际不会增加显存，但是现在的删除没有走标准流程，会导致资源统计有问题。
已经修改了

**Comment by lzsong** [comment]
调用destroy是可以释放掉这个RenderSprite，但是序列帧+mask会非常频繁的创建和销毁RenderSprite，游戏中挂一会机就会Resource.id自增几十万了，你们可以先记录下，肯定还是需要优化的。
