### ISSUE TITLE
ShurikenParticle 材质Unity无法导出

### ISSUE THREAD

**Issue by KaiFengGame** [layabox/LayaAir#169]
如题 导出时提示
LayaAir3D Warning : ShurikenParticle must config in CustomShaderConfig File.

CustomShaderConfig.json这个文件我找了在LayaTool文件夹里。
但这个该怎么让开发者填写呢。填写的格式是什么才能导出。

**Comment by KaiFengGame** [comment]
等待laya回复

**Comment by aaronswiftming** [comment]
请把无法导出的 unity资源发来看看，并且标注工具版本，如果能更详细的描述 都怎么做的，属性列表之类的截图就能更好的判断您的问题。这个描述的太简略无法知道问题核心在哪。

**Comment by KaiFengGame** [comment]
不是吧老铁。您那里的unityshader中ShurikenParticle这个能导出？
我试过了unity5.6.7和unity2018.
laya2.1.1.1 到 laya2.4.0beta2 及对应的unity插件都试过了。均无法导出。
只有随便建一个cube 材质球选laya的ShurikenParticle就导不出来。
这还用发资源么 =。=！

**Comment by KaiFengGame** [comment]
<img width="1673" alt="导出后无lmat截图" src="https://user-images.githubusercontent.com/8076367/71948825-57aa5b00-320c-11ea-8077-43a0f377f2d8.png">
导出后无lmat截图

**Comment by aaronswiftming** [comment]
能导出来

**Comment by aaronswiftming** [comment]
这个是给粒子系统用的，不要给cube。 一开始就说清楚能好办许多，你不说自己咋做我都不知道你是做了错误操作，没工夫猜谜，请阅读git上如何正确的提问等文章

**Comment by aaronswiftming** [comment]
请注意言辞，全球的人都可能能看到对话，专业一点

**Comment by KaiFengGame** [comment]
也不知道您这玩意还可以这么玩的。粒子系统专属呗。别人用不了呗。好的。麻烦照顾新人，可以材质给个注释啥玩意的。也能坑数-1。或者导出的log人性化一点。谢谢您。

**Comment by lirongf** [comment]
我们会在laya插件后续加上这个提示
