### ISSUE TITLE
layabox 能不能通过 npm 发布

### ISSUE THREAD

**Issue by zsytssk** [layabox/LayaAir#170]
通过npm发布版本，我们直接通过`npm install @LayaAir/layaBox`来安装；安装升级版本也很简单，就像react的npm包；
(也可以将laya-cmd放到@LayaAir/cli 中，这样看起来更先进， 更时髦)

**Comment by Lurenyiabc** [comment]
有计划做，但是做的话也不会是这个项目。可能会是一些发布后的引擎包
