### ISSUE TITLE
无法使用Chrome运行

### ISSUE THREAD

**Issue by wje5** [layabox/layaair#18]

**Comment by Gamezpedia** [comment]
打开chorme快捷方式属性并添加：
“C：\ Program Files（x86）\ Google \ Chrome \ Application \ chrome.exe”--allow-file-access-from-files --allow-file-access --allow-cross-origin-auth-prompt

**Comment by yungzhu** [comment]
chrome打开本地文件有安全限制，解除安全限制，有以下方法：
1.添加楼上参数或者关闭chrome，用IDE调试打开chrome（ide会增加上述参数）
2.用http网站方式打开
