### ISSUE TITLE
Why TypeScript instead of Haxe?

### ISSUE THREAD

**Issue by RUSshy** [layabox/LayaAir#181]
Hi,

With Haxe you can target all paltforms, including web/console/mobile

Syntax is just like ActionScript, it is based from it

https://haxe.org/

**Comment by justinlm** [comment]
Because TypeScript is more fashion， in my opinion.

**Comment by RUSshy** [comment]
original LayaAit is written in AS3, Haxe is same syntax as AS3

**Comment by GuoLei1990** [comment]
em.....  How to say,we really like TypeScript better.

**Comment by RUSshy** [comment]
good, but now you limit only to web

haxe support web target, native target (c/c++, hashlink) and also consoles and mobiles
