### ISSUE TITLE
建议: 你们的ide也通过github来开发 就像vscode一样

### ISSUE THREAD

**Issue by zsytssk** [layabox/LayaAir#186]
建议: 你们的ide也通过github来开发 就像vscode, [egret](https://github.com/egret-labs/egret-ui-editor-opensource)一样 , 我们可以再上面提问题, 可以很快的得到反馈; 而且ide上可以直接带一个反馈功能 就像vscode一样, 这样更高效些.

**Comment by GuoLei1990** [comment]
感谢，我们会考虑您的建议
