### ISSUE TITLE
No IDE found how to setup the project ? 

### ISSUE THREAD

**Issue by Gamezpedia** [layabox/layaair#19]
Are you guys still working on this engine and IDE ? i found the old version of the IDE and it is written in Japanese or Chinese but not in English, and if you go to tutorials section it is using IDE to make project structure and yet in the master branch you can't even find the IDE executable also the IDE link on the main site is downloading source code of an android app i don't know what is going on with this engine i liked it because of Flash AS3 it seems that it is not for global developers.

**Comment by akimgacem** [comment]
Hi,

Engine and IDE are still in active status.

- Please find in attachment the process to config your IDE in english.
(Download latest version of Layair IDE : https://ldc.layabox.com/layadownload/?type=layaairide-LayaAir%20IDE%201.7.11%20beta )
1. Choose "en-US"
2. Click on restart to apply the language modification

- English Tutorials section can be found on the link below and translation is on going
https://ldc.layabox.com/doc/?language=en&nav=en-as-0-3-0


attachment : 
![setenglish](https://user-images.githubusercontent.com/20181779/31535159-93e50534-b02c-11e7-8e27-b40d8a5c3bc6.png)

**Comment by Gamezpedia** [comment]
Thanks found the latest one and it's perfect :) 👍
