### ISSUE TITLE
Atlas packaging tool not working in 1.7.11beta

### ISSUE THREAD

**Issue by Gamezpedia** [layabox/layaair#20]
it is just making a .rec file in the resource folder .

**Comment by akimgacem** [comment]
Hi,

If the export going well, you should have *.rec, *.atlas, *.png and *.json files.
In order to solve the issue, can you details us the step to reproduce the bug.

Atlas packaging tool is explain in this tutorial (Chinese version only at this moment) : 
http://ldc.layabox.com/doc/?nav=zh-as-2-2-0

**Comment by akimgacem** [comment]
Here the correctly process :
> user should select the folder which is the **parent folder of the folder** containing the picture files.
> it's because that we treat the folder containing pictures as a unit to pack an atlas, which name is the same as the folder's name.
> 

Let us know if after this you still have issues problem, and details the step of procedure making only a .rec file.

**Comment by Gamezpedia** [comment]
Hi, 
i followed the instructions but it is still making a .rec file .

**Steps i take to make atlas**:

1. made a folder on desktop called game
2. copied my png image assets in the folder
3.  goto to the LayaBoxIde > Tools > Atlas packing
4. 
![image](https://user-images.githubusercontent.com/1169093/31849607-57e5182a-b65e-11e7-9c34-4507aa56f137.png)
5. After clicking ok it will show generating progress but ends very quickly and shows Execution completed message.
6. but in the folder you can see 
![image](https://user-images.githubusercontent.com/1169093/31849636-b3781fc0-b65e-11e7-8ac5-df19cebafeed.png)

**Comment by Gamezpedia** [comment]
This method is **Working fine** 
**I also tried the other method which is generating Atlas :**

1. Imported the game folder into the Laya/assets/game
2. then pressed Ctrl + F12 to release the assets 
3. it created the folder res into the bin/h5 directory

thanks

**Comment by akimgacem** [comment]
You did right, but you choose select the parent folder of your png assets content. In your case should be "C:\Users\GamezPedia\Desktop"

Here is my implementation : 

1. Place your folder
-I have in my assets folder, my png frames in monkey folder as follows : "[ProjectName]/assets/monkey"
	[ProjectName] is the folder which contain your .laya project file and jsconfig.json

2. Let's convert it
-Open LayaAirIDE
- Click to menu then Tools > Atlas packing
- A Windows popup appears, drag your assets folder in it (see picture in attachment)
	you should have generated files .rec , .png (spritesheet ones), and .atlas(or .json)

In the windows popup you can set the "Data file suffix" whether you would like json or atlas file.
Article 
![drag](https://user-images.githubusercontent.com/20181779/31979489-460aec42-b947-11e7-95a3-8898d989363e.png)
english version 4.2 if you want to know "the difference between json and atlas" 
https://ldc.layabox.com/doc/?language=en&nav=en-as-2-2-0
