### ISSUE TITLE
又发现一种情况PBR材质在微信pc端内置浏览器中会出错

### ISSUE THREAD

**Issue by designerlyj** [layabox/LayaAir#209]
laya项目和unity项目在这个贴子中
https://ask.layabox.com/question/46057

**Comment by GuoLei1990** [comment]
https://github.com/layabox/LayaAir/commit/af86104ae3c7241f6145aa878f85656e2bada586 已修复

**Comment by designerlyj** [comment]
反应迅速，给力！
