### ISSUE TITLE
我对dialog遮罩控制关闭优化了下，这样是不是提交了，你们那能看到吗？

### ISSUE THREAD

**Issue by df257** [layabox/LayaAir#228]
![image](https://user-images.githubusercontent.com/7835444/80295593-8f7ee380-87a6-11ea-85ce-91abf0c7ac3c.png)

**Comment by whzooo** [comment]
github怎么了?图片看不见.

**Comment by df257** [comment]
> github怎么了?图片看不见.
我这边能看见，今天github意外的网速飞快。。。
