### ISSUE TITLE
laya 2.6 支持async 和 await么

### ISSUE THREAD

**Issue by joewan** [layabox/LayaAir#247]
laya 2.6 支持async和await么，应该如何配置呢

**Comment by eos3tion** [comment]
@joewan 
`async` `await`的支持和 `laya`无关  
原生支持需要支持`ecma2018`的js环境（浏览器环境），目前各小游戏平台的js环境都没有原生支持，ios11 android8 以上的手机自带webview都是支持的。  

如果你代码是用typescript写的，能很方便用`typescript`的编译器特性，transform出`es5`标准的`async` `await`，利用回调函数实现  
用js写的，也可以用`babel` 转义

**Comment by Lurenyiabc** [comment]
ts写需要改tsconfig，需要调整target和lib，还是比较麻烦的，比较推荐编译完之后直接用babel转。或者直接调整target和module至esnext，但是环境支不支持就另说了

**Comment by zsytssk** [comment]
你要自己用webpack打包， 我们公司的可以的。。。 先用ts转义成es6 再用bable转义成es5

**Comment by chiuan** [comment]
> 你要自己用webpack打包， 我们公司的可以的。。。 先用ts转义成es6 再用bable转义成es5
> [示例项目](https://github.com/zsytssk/tpl/tree/master/laya)

感觉还要另外一套东西。。。很恶心啊。。建议还是等各大平台很好支持吧
