### ISSUE TITLE
数组的slice方法非常不直观 ，建议两个参数都表示索引（下标）

### ISSUE THREAD

**Issue by zhuangce** [layabox/LayaAir#262]
slice(start?: number, end?: number): 
现在的情况是参数start为索引 ，参数end不是元素的索引，而是次序 ，这导致该方法的使用非常不友好。拖慢开发进度。

**Comment by eos3tion** [comment]
JS标准对象的问题不该发这里吧，你不习惯就自己封装个方法，难度又不大    
主流语言(c,java,python)，切片(slice)操作都是，`start`闭区间，`end`开区间，用来方便循环切片的

**Comment by zhuangce** [comment]
谢谢提醒哈 ，之前用c#没遇到过这样的api ，就觉得有点怪

**Comment by guozhaokui** [comment]
是的
