### ISSUE TITLE
在微信小游戏中无法加载场景文件

### ISSUE THREAD

**Issue by delguoqing** [layabox/layaair#27]
提示出错信息
Scene: the .lh file root type must be Scene,please use other function to  load  this file.

稍微跟了一下：
首先ls文件的类型是"SPRITE3DHIERARCHY"，没有作为json文件读入。
然后因为MiniLoader.load的实现没有支持customParser，所以不会递归去加载材质、MESH等资源。
求解决。

**Comment by yungzhu** [comment]
新版已经解决，多谢反馈
