### ISSUE TITLE
使用Sprite的drawToCanvas 参数带有小数点会导致错误

### ISSUE THREAD

**Issue by imfox** [layabox/layaair#33]
报错信息如下，没有小数点就不会报错
> Uncaught RangeError: Source is too large
>     at Uint8ClampedArray.set (<anonymous>)
>     at Function.RunDriver.drawToCanvas (bundle.js:24135)
>     at SButton.__proto.drawToCanvas (bundle.js:15002)
>     at Guide.<anonymous> (Guide.ts:26)
>     at TimerHandler.__proto.run (bundle.js:9492)
>     at Timer.__proto._update (bundle.js:9236)
>     at Stage.__proto.render (bundle.js:17820)
>     at Stage.__proto._loop (bundle.js:17778)
>     at loop (bundle.js:5219)

**Comment by yungzhu** [comment]
解决了，多谢反馈
