### ISSUE TITLE
小游戏中图片加载引擎可以支持区分下载方式吗

### ISSUE THREAD

**Issue by witthong** [layabox/LayaAir#33]
小游戏中使用图片加载的方式目前好像是先
downloadFile 之后 再 使用 image.src 加载。
引擎内部可以支持选择 image.src 直接加载网络图片的方式吗，不通过 downLoad file，
有些场景不想要增加小游戏的域名白名单

**Comment by GuoLei1990** [comment]
使用image.src也是要加白名单的

**Comment by witthong** [comment]
> 使用image.src也是要加白名单的

应该不用吧，文档上说明的是 
request/downloadFile/socket/uploadFile 等需要配置域名白名单

cocos 提供的方案是支持两种方式选择的，仅供参考

**Comment by layaxiaosong** [comment]
目前的处理图片下载我们用了微信的 donwloadfile接口，使用这个接口的目的就是为了缓存下载的图片，重复下载使用缓存的文件，所以需要在微信白名单里设置downloadfile。而window.Image.src 这个是既不用downloadfile ，也不用request，所以你不用设置白名单即可。你说的有些场景不想增加白名单，这里说的场景图片是4M包还是外网加载？如果需求大的话，后面我们会扩充一个数组，让开发者手动添加需要特殊处理的加载地址，跳过downloadfile接口，直接使用window.src完成图片的加载。
