### ISSUE TITLE
对MeshColliderShape进行射线检测结果不正确

### ISSUE THREAD

**Issue by designerlyj** [layabox/LayaAir#347]
如下图，白色方体是BoxColliderShape，检测正常，返回一个结果值
黄色方体是MeshColliderShape时，rayCastAll会返回两个结果值，而且返回结果的法线方向也不正确
![raycastbug](https://user-images.githubusercontent.com/24490533/89885145-2f993500-dbfd-11ea-9093-2d2770fcfed4.jpg)

论坛帖子：http://ask.layabox.com/question/47201

**Comment by lirongf** [comment]
我们已经去找物理引擎的这个bug  找到后第一通知您
