### ISSUE TITLE
Laya2.6.1升级Laya2.7.1，UI显示出错

### ISSUE THREAD

**Issue by Fantasy-Dm** [layabox/LayaAir#352]
https://github.com/layabox/LayaAir/blob/18b98135af981a6b10c9071a5dfec524d1314fbd/src/layaAir/laya/display/Node.ts#L764

经过对比前后代码，发现!child._getBit(Const.NOT_READY)) 这个判断在新增之后，会出现界面显示混乱的现象

**Comment by Fantasy-Dm** [comment]
2.6.1版本显示正常，是我需要修改什么地方来适配2.7.1的新版本逻辑嘛

**Comment by Fantasy-Dm** [comment]
查到问题了，只要是在scene中包含了一个view的节点的UI都会出现这个问题，将view换成Box类型就没这个问题了，麻烦看看能不能修复这个问题吧，现在出问题的UI太多了改不过来，只能放弃升级新版本了@houyi  @GuoLei

**Comment by guozhaokui** [comment]
能提供一个demo么，这样我们好找一些

**Comment by Lurenyiabc** [comment]
感谢反馈，可以参考以下提交修改
Duplicate of #354

**Comment by Fantasy-Dm** [comment]
> 能提供一个demo么，这样我们好找一些
![image](https://user-images.githubusercontent.com/8214383/91285673-1927d780-e7c0-11ea-8d01-410a45887b2d.png)
简单写了一个demo，上面这个就是2.7.1上出现的效果，同样的布局和代码在2.6.1里面的效果是这样的
![image](https://user-images.githubusercontent.com/8214383/91286590-30b39000-e7c1-11ea-9da3-a5b9e1767241.png)

2.6.1的demo工程：
[minitetris.zip](https://github.com/layabox/LayaAir/files/5128878/minitetris.zip)

**Comment by Fantasy-Dm** [comment]
> 感谢反馈，可以参考以下提交修改 #354

好的，不客气

**Comment by Fantasy-Dm** [comment]
> 感谢反馈，可以参考以下提交修改 #354

试了一下，改完以后就一片黑了，啥都不显示。。。

**Comment by Lurenyiabc** [comment]
再带上这个修改试试 #361

**Comment by Fantasy-Dm** [comment]
> 再带上这个修改试试 #361

嗯，试了一下应该是可以了，辛苦辛苦~
