### ISSUE TITLE
PrimitiveMesh类createQuad方法，vertices数组halfLong负号丢失

### ISSUE THREAD

**Issue by zjw552048** [layabox/LayaAir#43]
升级2.2版本后，发现PrimitiveMesh类createQuad方法，vertices数组第一个halfLong的负号丢失，导致mesh形状异常。

**Comment by GuoLei1990** [comment]
非常感谢，已修复！ https://github.com/layabox/LayaAir/commit/24c131908e1d6c7c5e2e4463c935176994730533
