### ISSUE TITLE
d.ts很多字段无法访问了

### ISSUE THREAD

**Issue by HiKit** [layabox/LayaAir#47]
Vector3._ZERO
ColliderShape.SHAPEORIENTATION_UPY
AnimatorControllerLayer._currentPlayState

很多类似的字段无法访问了，总不能自己维护一个d.ts吧，希望能够向下兼容

**Comment by GuoLei1990** [comment]
SHAPEORIENTATION_UPY 是注释错误被隐藏了，已修复https://github.com/layabox/LayaAir/commit/a458b2529e1fc13e9ad7015f6637e4067f617eb0 
其它的下划线变量我们是故意不让外部访问  这是ts的一种严谨模式功能"stripInternal": true。如果你想访问任何内部变量，但我们没有提供，可以告知我们，经过权衡会正式公开

**Comment by HiKit** [comment]
Vector3的UP ZERO等常量希望开放，不然要在项目内定义

**Comment by HiKit** [comment]
AnimatorControllerLayer希望开放currentPlayState，在一些逻辑下需要取动作原件，比如判断当前动作是否是循环动作，比如切换模型时需要处理动作同步
类似如下：
`if (oldAnimator && this._animator) {
                    let state: Laya.AnimatorState = oldAnimator.getControllerLayer()._currentPlayState;
                    let playState: Laya.AnimatorPlayState = oldAnimator.getCurrentAnimatorPlayState();
                    if (state && playState) {
                        this._animator.play(state.name, 0, playState.normalizedTime);
                    }
                }`

**Comment by GuoLei1990** [comment]
在 8061aceddef4e5abec50641177e3f4f06023c3b7 提交中公开了当前播放状态机,具体使用方式为 animator.getControllerLayer().getCurrentPlayState().animatorState，统一归类到动画播放状态信息中

**Comment by GuoLei1990** [comment]
Vector3的UP ZERO屏蔽的原因是因为在JS中无struct概念,vector3为class,公开Vector3.UP是一种极其危险的做法，开发者会经常无意中修改Vector3.UP,导致Vector3.UP值并非（0，1，0），连锁导致所有引用此变量的计算全都崩溃。通常像C#这种有struct概念的语言 我们会将vector3设计为struct，而非class,公开Vector3的UP和ZERO非常安全易用，但在LayaAir中由于我们采用TS（JS）语言，很遗憾，我们不能这么做。

**Comment by HiKit** [comment]
> Vector3的UP ZERO屏蔽的原因是因为在JS中无struct概念,vector3为class,公开Vector3.UP是一种极其危险的做法，开发者会经常无意中修改Vector3.UP,导致Vector3.UP值并非（0，1，0），连锁导致所有引用此变量的计算全都崩溃，我们曾收到大量疑似BUG的反馈均由此导致。通常像C#这种有struct概念的语言 我们会将vector3设计为struct，而非class,公开Vector3的UP和ZERO非常安全易用，但在LayaAir中由于我们采用TS（JS）语言，很遗憾，我们不能这么做。

了解了，这种我项目内自己定义。

**Comment by eos3tion** [comment]
@GuoLei1990 
`ts`是可以用  [Readonly](https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#improvements-for-readonlyarray-and-readonly-tuples)标记，
也可以利用[Object.freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)
```ts
Vector3.UP = Object.freeze(new Vector3(0,1,0));
```
把属性锁定，防止修改
我也觉得你们写法并不是最舒服的

**Comment by GuoLei1990** [comment]
@eos3tion Readonly标记可以防止 Vector3.UP =new Vector3(100,100,100);但无法防止Vector3.UP.x=100,依然会造成Vector3.UP的实际值变化

**Comment by eos3tion** [comment]
@GuoLei1990 Readonly<T> 这个是可以的，你看下我上面那个对应的链接
https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#improvements-for-readonlyarray-and-readonly-tuples

**Comment by GuoLei1990** [comment]
@eos3tion  很棒 试了一下 使用readonly UP: Readonly<Vector3> 确实可以防止Vector3.UP.x=100。但另一个比较常见的风险还是无法规避。 
例如：
var out=Vector3.ZERO;
Vector3.add(a,b,out);

不过 Readonly<T>可能会对其它API的设计有帮助

**Comment by eos3tion** [comment]
@GuoLei1990 这种，tsservice目前没法直接报错，不过用Object.freeze是能强制锁死属性的。这种倒是不怕被误用，修改 Vector3.ZERO的属性

**Comment by GuoLei1990** [comment]
@eos3tion  目前看功能是可行的,我们需要对Object.freeze的性能进行一下测试,如果没有发现问题，后续可能会应用此方法
