### ISSUE TITLE
抱歉,借宝地问下 layaair-cmd 是否有人维护(进论坛需要上交手机和微信).

### ISSUE THREAD

**Issue by cupen** [layabox/LayaAir#492]
Hi 暂时先别关这个 issue , 请耐心听我说.
我本人用 linux 做开发, 翻过 [论坛] 得知官方是不支持的, 考虑到两点:
1. 我需求很单一, 只用 layaair-cmd 导出 UI 文件, 不用别的高级功能.
2. 我比较能折腾, 工程类的工具随便改改也能支持 linux.

于是我霸王硬上弓, 下载安装之 `npm install layaair-cmd -g`，但看起来还包含二进制文件( windows 和 mac).
```
tree /usr/lib/node_modules/layaair-cmd/ProjectExportTools/TP/
/usr/lib/node_modules/layaair-cmd/ProjectExportTools/TP/
├── atlas-generator
├── atlas-generator.exe
├── imageformats
│   ├── qgif.dll
│   ├── qicns.dll
│   ├── qico.dll
│   ├── qjpeg.dll
│   ├── qsvg.dll
│   ├── qtga.dll
│   ├── qtiff.dll
│   ├── qwbmp.dll
│   └── qwebp.dll
├── libgcc_s_dw2-1.dll
├── libstdc++-6.dll
├── libwinpthread-1.dll
├── Qt5Core.dll
├── Qt5Gui.dll
├── QtCore
└── QtGui

1 directory, 18 files
```
这个 `layaair-cmd` 最后一次更新是在三年前.
这里我的问题是:
目前它还有人维护不? 如果没人维护可否考虑下开源?

祝大家身体健康,多多发财.

[论坛]: https://ask.layabox.com/question/42031

**Comment by Lurenyiabc** [comment]
有计划开源

**Comment by cupen** [comment]
@Lurenyiabc 静侯佳音.

**Comment by cupen** [comment]
好的, 感谢.  我看到那个项目了. 
只是携带了太多二进制文件, 有点懵.  这个 issue 我就关掉了.
https://github.com/a7359475/layaair-cmd/issues/6
