### ISSUE TITLE
使用2.2.0引擎时遇到了一个偶现的bug，原因应该是这一行代码缺少 data是否存在的判断

### ISSUE THREAD

**Issue by sssssssh** [layabox/LayaAir#56]
https://github.com/layabox/LayaAir/blob/6204a20df3739b35a11978b878a27b4617ea1c57/src/layaAir/laya/net/Loader.ts#L418

**Comment by aaronswiftming** [comment]
直接把修改后的 提交吧，我们审一下，最好有复现demo
