### ISSUE TITLE
封装物理引擎bullet的接口部分缺少源码 无法进行调试开发

### ISSUE THREAD

**Issue by grant930** [layabox/LayaAir#57]
Rigidbody3D.ts中的代码：
var motionState: any = new physics3D.LayaMotionState();
具体代码实现能否公开？ 有修改bullet库的需求。thx

**Comment by GuoLei1990** [comment]
LayaMotionState 是没有C++代码实现的,是采用emsdk在js中模拟了对C++对象的继承，我可以给你IDL文件的声明代码
[JSImplementation="btMotionState"]
interface LayaMotionState {
  void LayaMotionState();
  void getWorldTransform([Ref] btTransform worldTrans);
  void setWorldTransform([Const, Ref] btTransform worldTrans);
};

**Comment by grant930** [comment]
@GuoLei1990 非常感谢。目前也是通过JSImplementation来实现对其他接口的继承。还有一个相关问题， 针对bullet的版本laya采用的是2.82还是2.83？有没有需要额外注意的地方

**Comment by GuoLei1990** [comment]
目前bullet版本是2.87版本,我们对bullet源码做了一点修改，应该问题不大，你们可以试试。

**Comment by grant930** [comment]
@GuoLei1990 
在用修改ammo工程后的idl构建成功并替代laya.physics3D.js , 运行后有报错：
laya.d3.js:31995 Uncaught TypeError: physics3D(...).then is not a function
    at Function.init (laya.d3.js:31995)
    at new Main (bundle.js:294)

定位到这一行：
physics3D(config.defaultPhysicsMemory * 1024 * 1024).then(function () {

请问是否还需要额外处理？ 我们只是想开放几个bullet的接口，简单替换掉laya.physics3D.js 貌似不行

**Comment by GuoLei1990** [comment]
我们已经优化了物理引擎部分  你可以克隆一下最新的代码，你现在的修改可能对引擎来说可能已经过时了

**Comment by GuoLei1990** [comment]
@grant930 编译后需要微调一下
 (1)编译后调整构造函数参数为memorySize参数。
    (2)第一行function(memorySize)前插入window.Physics3D=
    (2)"Physics3D=Physics3D||{}"替换为"Physics3D={}"。 
    (3)需查找TOTAL_MEMORY关键字替换固定16M内存常量为memorySize参数。
    (4)去掉Laya.Physics3D前的this,改外window.Physics3D
    (5)去掉_currentScript相关两行代码支持微信小程序
这是我们以前的修改文档

**Comment by grant930** [comment]
裁剪后的版本变化很大，想问下目前是否还有计划中的大变动？ 假如继续使用2.3.0版本的物理库是否有比较大风险？

**Comment by GuoLei1990** [comment]
暂时不会有大变动,
但必须注意物理库和引擎库的版本必须保持一致
