### ISSUE TITLE
2.0.0beta4模态对话框关闭后遮罩不消失

### ISSUE THREAD

**Issue by yblunan** [layabox/layaair#60]
Laya.Dialog.load ("message.scene", Laya.Handler.create(this, (dlg: Laya.Dialog)=> {
	dlg.popup();
}));

message上有个按钮 name为"ok"

**Comment by dashaomai** [comment]
不用popup方式，用show打开

**Comment by yblunan** [comment]
> 不用popup方式，用show打开

朋友，用popup打开的是模态对话框，有遮罩。
open和show打开的是普通窗口，没有遮罩啊

**Comment by dashaomai** [comment]
我们查一下引擎，然后修复这个bug

**Comment by dashaomai** [comment]
能在社区提交一个demo吗，好更好的知晓你遇到的问题。

**Comment by yungzhu** [comment]
多谢反馈，已经修复
