### ISSUE TITLE
Trail问题

### ISSUE THREAD

**Issue by eos3tion** [layabox/LayaAir#61]
目前使用Laya的Unity插件，导出Trail资源，发现参数
`TrailSprite3D.ts`中`_parse`方法
https://github.com/layabox/LayaAir/blob/master/src/layaAir/laya/d3/core/trail/TrailSprite3D.ts#L51-L99

`data.alignment`和`.lm`资源中属性对不上，Unit插件导出的属性是`AlignMent`，大小写不匹配

另外`_cloneTo`方法，并没有复制`alignment`属性

**Comment by GuoLei1990** [comment]
https://github.com/layabox/LayaAir/commit/50a69af76a258e38eb08674a260c92bf164581b2 克隆问题已修复 
插件问题会在下个版本修复
