### ISSUE TITLE
2.0.0beta4 Uncaught Can not find class laya.effect.GlowFilterSetter undefined

### ISSUE THREAD

**Issue by yblunan** [layabox/layaair#61]
编辑器为label添加 GlowFilter组件，
编辑器效果正常
运行时报错
Uncaught Can not find class laya.effect.GlowFilterSetter
undefined

已经引入"laya.filter.js"

自己用代码new laya.GlowFilter能正常使用
，，应该是编辑器使用的类没有发布到bin
其它两个filter未测试

**Comment by dashaomai** [comment]
目前只能预览，还不能使用

**Comment by yblunan** [comment]
自己写了个脚本，运行有效
可惜不能预览
哈哈

**Comment by yungzhu** [comment]
少提交了类库，下次发布补上
