### ISSUE TITLE
如何从源码构建引擎

### ISSUE THREAD

**Issue by Geequlim** [layabox/LayaAir#64]
如何从该项目构建出Laya的各个JS库，即如何从源码生成
`laya.core.js`
`laya.ui.js`

**Comment by aaronswiftming** [comment]
\LayaAir\layaair\publish\LayaAirPublish\publibs   路径下 先双击 install.bat 安装一次，
之后编译源码 双击publish.bat
每次编译之前要把bin目录的老库删除
