### ISSUE TITLE
很遗憾 

### ISSUE THREAD

**Issue by 13592468736** [layabox/LayaAir#65]
“很遗憾，因您使用的当前设备或浏览器无法支持视频功能，本程序将无法继续，请您更换浏览器或其他设备来访问本程序，以获得最佳浏览体验。单击鼠标或点击屏幕即可退出。“”  crome浏览器出现这个怎么解决

**Comment by aaronswiftming** [comment]
以目前来看升级一下浏览器版本或者设备就能解决
