### ISSUE TITLE
预烘焙骨骼动画的旋转坐标计算可能存在BUG

### ISSUE THREAD

**Issue by fy0** [layabox/LayaAir#676]
mixamo 上弄了个小人动作，预烘焙一下之后导进引擎，结果喝醉了酒一样东倒西歪，不烘焙的话就好好地。

把所有关键帧的rotation删掉之后就不歪了。就是效果太差，推测可能这里有BUG，请维护人员帮忙看看？？

-----

另外骨骼节点的坐标是正常的，因为头顶上挂了个帽子，帽子动作幅度基本正常，但是角色本身歪了。

**Comment by QTED** [comment]
能麻烦提供个demo 资源吗，

**Comment by fy0** [comment]
> 能麻烦提供个demo 资源吗，

之前发论坛了，就这个 http://ask.layabox.com/question/48988

**Comment by fy0** [comment]
请问有消息了吗？换了个模型又试了一次 还是有问题。动作是从mixamo上弄的

用unity2018也试过 同样是不行。

另外cocos可以

**Comment by QTED** [comment]
确认了一下，是动画数据层级bug， 后续版本会修复
