### ISSUE TITLE
UI Problem

### ISSUE THREAD

**Issue by smkplus** [layabox/layaair#68]
I try to export Unity UI but not work in laya box

**Comment by akimgacem** [comment]
Unity UI is not supporting. only 3D assets, Camera, Light, Particle, Terrain, trail render components are available for export.
If you want work with UI, we advice you to use LayaAir IDE.
https://ldc2.layabox.com/layadownload/?language=en&type=layaairide-LayaAir%20IDE%202.0.0%20beta5
