### ISSUE TITLE
Layabox UI In English

### ISSUE THREAD

**Issue by aammfe** [layabox/layaair#7]
Hi!

i m instructed in your great product but
i m NOT Chines , and could not found IDE in English.

then i try to ask question on your forum , 
"How to convert IDE  to English "
but first, i have to register and , i could not sign Up there because they were asking Phone number , as i mentioned i m not chines ,
so i could not registered.

plz help me to sort out.

**Comment by akimgacem** [comment]
Hello, 
Thanks for your interest on LayaAirIDE, 
Software in english version have been added in our "to do list", and will be soon available.
However We have technical support on QQ messenger group : 104144216

Feel free to pm me if you need help with LayaAir API.

**Comment by akimgacem** [comment]
LayaAir is now available in english version , details issues are solve in ticket 19 :
https://github.com/layabox/layaair/issues/19
