### ISSUE TITLE
请问remapGLPositionZ的作用什么

### ISSUE THREAD

**Issue by InJoins** [layabox/LayaAir#72]
是因为什么硬件不兼容吗？
能否说说加入这个函数的意义和为什么加入了这个函数的细节原因吗？

PS：用TS改写，然后用开源方式和引擎用户交互，谢谢你们的贡献！

**Comment by GuoLei1990** [comment]
这个函数是为了兼容 webgl的Z深度标准 DX的标准是0到1  opengl/webgl 是-1到1  我们的投影矩阵采用0到1的标准 所以需要准换再输出到webgl 这个函数就是这个目的。 LayaAir未来的设计是兼容多种图形API （例如webgpu），会隐藏该函数和任何图形Api差异造成的内部转换，目前这部分的设计尚未完善 ，需要开发者手动调用转化Z深度

**Comment by InJoins** [comment]
谢谢🙏 很详细…明白了！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: GuoLei <notifications@github.com&gt;
发送时间: 2019年10月19日 23:21
收件人: layabox/LayaAir <LayaAir@noreply.github.com&gt;
抄送: InJoins <injoins@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[layabox/LayaAir] 请问remapGLPositionZ的作用什么 (#72)




这个函数是为了兼容 webgl的Z深度标准 DX的标准是0到1  opengl/webgl 是-1到1  我们的投影矩阵采用0到1的标准 所以需要准换再输出到webgl 这个函数就是这个目的。 LayaAir未来的设计是兼容多种图形API （例如webgpu），会隐藏该函数和任何图形Api差异造成的内部转换，目前这部分的设计尚未完善 ，需要开发者手动调用转化Z深度
