### ISSUE TITLE
请问3D物理引擎部分的代码有没有再压缩和裁剪的可能

### ISSUE THREAD

**Issue by InJoins** [layabox/LayaAir#73]
现在物理引擎有1.4M

如果我只需要用到射线检测部分，有没有可能裁剪呢

**Comment by GuoLei1990** [comment]
目前内部正在重构新版物理引擎库，目前由于某些问题还不能发布，成熟后会发布，时间暂时未定。全功能物理库仅750K左右

**Comment by InJoins** [comment]
期待！这部分工作是开创性的！其它引擎还没发现已经裁剪好的！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: GuoLei <notifications@github.com&gt;
发送时间: 2019年10月19日 23:04
收件人: layabox/LayaAir <LayaAir@noreply.github.com&gt;
抄送: InJoins <injoins@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[layabox/LayaAir] 请问3D物理引擎部分的代码有没有再压缩和裁剪的可能 (#73)




目前内部正在重构新版物理引擎库，目前由于某些问题还不能发布，成熟后会发布，时间暂时未定。全功能物理库仅750K左右
