### ISSUE TITLE
新版物理库只有不到750KB了！请问怎么做到的？

### ISSUE THREAD

**Issue by InJoins** [layabox/LayaAir#79]
请问只是编译参数的调整吗？还是说手动修改了BULLET的代码

另外就是编译出来的BULLET JS版，性能跟原生比，有多大的变化

能否提供一些概念分享，很好奇这一块
谢谢！我不是友商，我是引擎用户。

**Comment by GuoLei1990** [comment]
移除了无用接口,优化了粘合层。 JS版肯定不如原生，相对来说wasm版比较可观

**Comment by InJoins** [comment]
谢谢解惑。
WASM各种小游戏平台会支持不，大概哪年能支持，你们有消息吗

**Comment by GuoLei1990** [comment]
小游戏目前不支持的主要原因应该是苹果的JSCore不支持，这个目前还没有什么消息，但非小游戏平台几乎没有任何问题

**Comment by InJoins** [comment]
谢谢

**Comment by InJoins** [comment]
对了 新版的物理库支持CCD碰撞检测了吗

**Comment by GuoLei1990** [comment]
https://layaair2.ldc2.layabox.com/demo2/?language=en&category=3d&group=Physics3D&name=PhysicsWorld_ContinueCollisionDetection 旧版就支持
