### ISSUE TITLE
QQ小游戏打包，安卓手机预览不能打开

### ISSUE THREAD

**Issue by ferrydjing** [layabox/LayaAir#99]
QQ小游戏打包，安卓手机预览不能打开， QQ开发者工具真机调试也没有任何打印， ios是正常得

**Comment by eos3tion** [comment]
@ferrydjing  你是不是监听 onShow 作为游戏启动的入口，Android上，最好主动调用一下启动函数

**Comment by ferrydjing** [comment]
> @ferrydjing 你是不是监听 onShow 作为游戏启动的入口，Android上，最好主动调用一下启动函数

没有使用onshow作为游戏启动入口，启动入口是用的laya的onOpened
